global:
  scrape_interval:     15s
  evaluation_interval:  15s

scrape_configs:
  - job_name: 'dkp_monitor'
    metrics_path: /metrics
    honor_labels: true
    static_configs:
      - targets:
        - 'dkp_crawler:2025'